name:                waves-crypto
version:             0.1.0.0
github:              "disfenoid/waves-crypto"
license:             WTFPL
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/disfenoid/waves-crypto#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- base58-bytestring
- base64-bytestring
- cryptonite
- elliptics
- memory
- text

library:
  source-dirs: src
  exposed-modules:
  - Waves.Crypto